---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxy_m.
--- DateTime: 2019/12/12 8:57
---
---我们指定了 Lua 的解释器 /usr/local/bin directory。加上 # 号标记解释器会忽略它。接下来我们为脚本添加可执行权限，并执行：
---#!/usr/local/bin/lua
---
---

print("hello world!")
--print("hello world!")
-- 单行注释
--[[
多
行
注
释

]]--

--Lua 标示符用于定义一个变量，函数获取其他用户定义的项。
--标示符以一个字母 A 到 Z 或 a 到 z 或下划线 _ 开头后加上0个或多个字母，下划线，数字（0到9）。
--最好不要使用下划线加大写字母的标示符，因为Lua的保留字也是这样的。
--Lua 不允许使用特殊字符如 @, $, 和 % 来定义标示符。
--Lua 是一个区分大小写的编程语言。因此在 Lua 中 Runoob 与 runoob 是两个不同的标示符
